### ISSUE TITLE
MW 1.43: CodeEditor shows cursor in wrong location

### ISSUE THREAD

**Issue by nicjansma** [sarna-net/sarna-issues#16]
The cursor is displayed far to the right of the text:

![Image](https://github.com/user-attachments/assets/1245bfef-1ae2-4344-8721-6c7bd840f5d6)

If you switch back to non-CodeEditor, you can see the cursor is at the right place:

![Image](https://github.com/user-attachments/assets/d9fc1268-8560-4cf1-801f-90a54bfb13db)

Could be this issue: https://phabricator.wikimedia.org/T358971

**Comment by nicjansma** [comment]
Notice the CodeEditor didn't have a mono-spaced font.

Fixed with some manual CSS:

```css
// Taken from: https://stackoverflow.com/a/64077083/43815
.ace_editor, .ace_editor * {
    font-family: "Monaco", "Menlo", "Ubuntu Mono", "Droid Sans Mono", "Consolas", monospace !important;
    font-size: 12px !important;
    font-weight: 400 !important;
    letter-spacing: 0 !important;
}
```

![Image](https://github.com/user-attachments/assets/ba40c4ea-41a5-41c4-a9fb-f1d751724763)
