### ISSUE TITLE
References make spacing weird

### ISSUE THREAD

**Issue by Deadfire-** [sarna-net/sarna-issues#39]
**Describe the bug**
As brought up by csdavis on our discord:

_The 2nd thing is almost silly to bring up, but if it's related to other things it might be good to know. It seems that anytime there's a superscript in a line, the spacing is a little wider._

**To Reproduce**
Seen on every page that has references

**Expected behavior**
Old behavior was that the superscript would show inline and not increase line spacing.

**Screenshots**
![line_spacing.jpg](https://github.com/user-attachments/assets/32def30c-9219-44e1-b6ad-a41ae8dd3649)

![superscript.jpg](https://github.com/user-attachments/assets/fc33fbc7-bc1a-4bd0-9d9c-cef1dbe5651f)

**Additional context**
Information on a fix (and making the references responsive) could be found here: https://mediawiki.org/wiki/Help:Cite

**Comment by nicjansma** [comment]
Fixed with: https://www.mediawiki.org/wiki/Topic:Rcs0u0h5uh1rgbik plus an additional fixed for _References_ section

```css

#bodyContent {
    sup, sub {
        font-size: smaller;
        vertical-align: baseline;
        position: relative;
        line-height: normal;
    }

    sup {
        bottom: 0.33em;
    }

    sub {
        bottom: -0.25em;
    }
}
```

Before:

![Image](https://github.com/user-attachments/assets/3e29abd4-096b-49f5-bcc8-1599e40a8977)

After:

![Image](https://github.com/user-attachments/assets/62e0c48d-f4df-4aa7-8226-ed31ffdcc0ba)
